name: Compile LaTeX and Upload PDF

on:
  push:
    paths:
      - 'figures/*/.tex'  # Trigger the workflow when any .tex file in the figures directory or its subdirectories is modified

#on:
#  push:
#    branches:
#      - main  # or the branch you want to trigger the action on
#  pull_request:

jobs:
  compile_and_upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Compile LaTeX
      run: |
        cd figures
        for file in *.tex; do
          pdflatex -interaction=nonstopmode -halt-on-error "$file"
        done
      
    - name: Move PDFs to figures directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/figures
        find . -name '*.pdf' -exec mv {} $GITHUB_WORKSPACE/figures \;
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-compile LaTeX to PDF"
        branch: ${{ github.ref }}
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
